# Generated by Django 4.2.16 on 2024-09-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investmentmanager', '0002_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='language',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='style',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactiontype',
            field=models.CharField(default='deposit', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
